import axios from 'axios';

const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
const FETCH_ALL_POST_COMMENTS = "FETCH_ALL_POST_COMMENTS";
const ADD_NEW_POST = "ADD_NEW_POST";

// action creator -- generated by axios.action returns a response and pass it into action creator as parameter
const fetchAllPosts = (posts) => {
  console.log("-------fetching all posts ---------");
  return {
    type: FETCH_ALL_POSTS,
    payload: posts
  }
}

const addNewPost = (post) => {
  return {
    type: ADD_NEW_POST,
    payload: post
  }
}

const fetchAllPostsComments = (comments) => {
  console.log("fetchAllPostsComments=",comments);
  return {
    type: FETCH_ALL_POST_COMMENTS,
    payload: comments
  }
}


// thunk creator
export const fetchAllPostsThunk = () => (dispatch) => {
  console.log("are we here? ");
  return axios
    .get("/api/posts")
    .then(response => dispatch(fetchAllPosts(response.data)))
    .catch(err => console.log(err));
}

export const addNewPostThunk = (post, userId) => (dipatch) => {
  return axios
    .post("/api/users/1/posts")
    .then(response => dipatch(addNewPost(response)))
    .catch(err => console.log(err));
}

export const fetchAllPostCommentsThunk = (postId) => (dispatch) => {
  return axios
    .get("/api/posts/4/comments")
    .then(response => dispatch(fetchAllPostsComments(response))
    )
    .catch(err => console.log(err));
}

export default (state = [], action) => {
  switch (action.type) {
    case FETCH_ALL_POSTS:
      return action.payload;
    case ADD_NEW_POST:
      return [...state, action.payload];
    case FETCH_ALL_POST_COMMENTS:
      console.log("export=",[action.payload] );
      return action.payload;
    default:
      return state;
  }
}
